import fs from "fs";
import path from "path";

export type BrokerProvider = "icici" | "angel" | "dhan" | "fyers" | "zerodha" | "groww";

// In the packaged Electron app, electron/main.js sets OCP_USER_DATA_DIR to
// a per-user, always-writable folder (Electron's app.getPath('userData')).
// The app's own install folder (process.cwd() after the chdir in main.js)
// can be read-only to a normal user — e.g. when installed under
// C:\Program Files, which requires Administrator rights to write to — so
// .env.local must live in userData, not next to the app itself.
export function configDir(): string {
  return process.env.OCP_USER_DATA_DIR || process.cwd();
}

// Builds the .env.local content for one provider + credential set. Shared
// by the manual "paste your keys" POST handler and the Fyers in-app OAuth
// callback, so both write config the exact same way and never drift.
export function buildEnvVars(provider: BrokerProvider, credentials: Record<string, string>): Record<string, string> {
  const envVars: Record<string, string> = { BROKER_PROVIDER: provider };
  if (provider === "icici") {
    envVars.ICICI_API_KEY = credentials.apiKey || "";
    envVars.ICICI_SECRET_KEY = credentials.secretKey || "";
    envVars.ICICI_SESSION_TOKEN = credentials.sessionToken || "";
  } else if (provider === "angel") {
    envVars.ANGEL_API_KEY = credentials.apiKey || "";
    envVars.ANGEL_SECRET_KEY = credentials.secretKey || "";
    envVars.ANGEL_CLIENT_CODE = credentials.clientCode || "";
    envVars.ANGEL_PASSWORD = credentials.password || "";
    envVars.ANGEL_TOTP_SECRET = credentials.totpSecret || "";
  } else if (provider === "dhan") {
    envVars.DHAN_ACCESS_TOKEN = credentials.accessToken || "";
    envVars.DHAN_CLIENT_ID = credentials.clientId || "";
  } else if (provider === "fyers") {
    envVars.FYERS_APP_ID = credentials.appId || "";
    envVars.FYERS_SECRET_ID = credentials.secretId || "";
    envVars.FYERS_ACCESS_TOKEN = credentials.accessToken || "";
  } else if (provider === "zerodha") {
    envVars.KITE_API_KEY = credentials.apiKey || "";
    envVars.KITE_API_SECRET = credentials.apiSecret || "";
    envVars.KITE_ACCESS_TOKEN = credentials.accessToken || "";
  } else if (provider === "groww") {
    envVars.GROWW_ACCESS_TOKEN = credentials.accessToken || "";
    envVars.GROWW_CLIENT_ID = credentials.clientId || "";
  }
  return envVars;
}

// Writes credentials to .env.local AND applies them to the running process
// immediately (no restart needed). Used by both the manual "Save Keys"
// button and the Fyers OAuth callback, so a completed in-app login takes
// effect exactly the same way a manually-pasted token would.
export function writeBrokerConfig(provider: BrokerProvider, credentials: Record<string, string>) {
  const envVars = buildEnvVars(provider, credentials);
  const lines: string[] = [
    "# Option Chain Pulse — Broker API Keys",
    "# Generated by the in-app API Keys dialog",
    ...Object.entries(envVars).map(([k, v]) => `${k}=${v}`),
  ];
  const dir = configDir();
  fs.mkdirSync(dir, { recursive: true });
  const envPath = path.join(dir, ".env.local");
  fs.writeFileSync(envPath, lines.join("\n"), "utf-8");
  for (const [k, v] of Object.entries(envVars)) process.env[k] = v;
}
